feat (YH-158) make a layout of the list of questions block
YeaHubTeam/yeahub-platform pull request #10
Opened 2024-06-09 19:38 UTC by beckyuldashev

Списку нужен скролл? Просто сейчас больше 3 элементов не влезает. У нас всегда там будет только 3 вопроса?

Вот так пока выглядит компонент:
![image](https://github.com/YeaHubTeam/yeahub-platform/assets/60789378/d1ccd866-3cc0-4bb4-ac3e-224667c358d1)

2024-06-09 20:58 UTC, PerelomaDenis requested changes

2024-06-09 20:58 UTC, PerelomaDenis commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsList/InterviewQuestionsList.tsx
> +const interviewQuestionsData = [
Структура вопросов не такая. Вот как выглядит вопрос 
![image](https://github.com/YeaHubTeam/yeahub-platform/assets/88330372/79353b63-c968-4804-b106-bc840d45853f)
Сложность это поле rate
Рейтинга пока нет - дефолтное значение 10, но думаю можно обозвать покаэто поле rating

2024-06-09 20:58 UTC, PerelomaDenis commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsList/InterviewQuestionsList.tsx
> +				<InterviewQuestionsItem key={id} {...props} />
Почему id не прокидывается внутрь компонента? Он там нужен для того, чтобы перейти на деталку вопроса.

2024-06-09 20:58 UTC, PerelomaDenis commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsItem/InterviewQuestionsItem.tsx
> +			<Link to={`/interview/${link}`} className={styles.link}>
url дял перехода на деталку выглядит так /question/${id}

2024-06-09 20:58 UTC, PerelomaDenis commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsItem/InterviewQuestionsItem.tsx
> +export const InterviewQuestionsItem: FC<Props> = ({ link, src, title, params }) => {
Я думаю лучше прокидывать не отдельными пропсами все элементы вопроса, а полностью объект одним пропсом

2024-06-09 20:58 UTC, PerelomaDenis commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsList/InterviewQuestionsList.tsx
> +			{interviewQuestionsData.map(({ id, ...props }) => (
Я бы убрал деструктуризацию и прокинул целиком объект вопроса

2024-06-09 20:58 UTC, PerelomaDenis commented on src/widgets/InterviewQuestions/ui/InterviewQuestionHeader/InterviewQuestionHeader.tsx
> +export const InterviewQuestionHeader: FC<Props> = ({ title, linkTitle }) => {
Здесь либо вообще не указывать пропсы и все прописать в jsx. Либо выносить как универсальную компоненту и добавлять к пропсам ссылку, так как похожий блок будет и в других блоках страницы интервью

2024-06-09 20:58 UTC, PerelomaDenis commented on src/widgets/InterviewQuestions/ui/InterviewQuestionHeader/InterviewQuestionHeader.tsx
> +				<Link to="/interview/questions" className={styles.link}>
И ссылка судя по всему должна вести на /questions

2024-06-09 20:58 UTC, PerelomaDenis commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsItem/InterviewQuestionsItem.tsx
> +export interface Props {
Название пропсов состоит из - Название компонента + Props

2024-06-09 20:58 UTC, PerelomaDenis commented on src/pages/InterviewPage/ui/InterviewPage.tsx
> +			<Block></Block>
Компонент Block очень тяжелый. Он сюда не подходит. Создай в shared компонент Card, в котором просто будет обертка вот прмиерно с такими стилями 
![image](https://github.com/YeaHubTeam/yeahub-platform/assets/88330372/0cae6c61-443b-4f74-af25-2376c984619d)

2024-06-10 10:07 UTC, PerelomaDenis commented
> Списку нужен скролл? Просто сейчас больше 3 элементов не влезает. У нас всегда там будет только 3 вопроса?
> 
> Вот так пока выглядит компонент: ![image](https://private-user-images.githubusercontent.com/60789378/338005145-d1ccd866-3cc0-4bb4-ac3e-224667c358d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTQzMzcsIm5iZiI6MTcxODAxNDAzNywicGF0aCI6Ii82MDc4OTM3OC8zMzgwMDUxNDUtZDFjY2Q4NjYtM2NjMC00YmI0LWFjM2UtMjI0NjY3YzM1OGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDEwMDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMWQ0ZjQ1ZDkyZTRkZDQ0OTJmOGJmN2QwNzcwZjIwZTE3YmJlODdjYTNjNDUwMjQ4NzM2ZGU0MmM3OWFiMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O_8erHzn41gGKaQSerkbJxkyWZc89EHfFaJ1TILU7PU)

Я думаю, что здесь будут выводиться 3 рандомных вопроса

2024-06-10 18:43 UTC, beckyuldashev commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsItem/InterviewQuestionsItem.tsx
> +export const InterviewQuestionsItem: FC<Props> = ({ link, src, title, params }) => {
Тогда здесь же создать QuestionProps, который будет выглядит следующим образом:
```
interface QuestionProps {
	id: number;
	title: string;
	description: string;
	keywords: string[];
	shortAnswer: string;
	longAnswer: string;
	status: string;
	rate: number;
	rating: number;
	specializations: number[];
	skills: number[];
	imageSrc?: string;
}

interface Props {
	question: QuestionProps;
}
```

2024-06-10 18:43 UTC, beckyuldashev commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsItem/InterviewQuestionsItem.tsx
> +			<Link to={`/interview/${link}`} className={styles.link}>
А разве не /questions/${id}

2024-06-10 18:43 UTC, beckyuldashev commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsList/InterviewQuestionsList.tsx
> +const interviewQuestionsData = [
Хорошо, сделаю в таком формате

2024-06-10 18:43 UTC, beckyuldashev commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsList/InterviewQuestionsList.tsx
> +			{interviewQuestionsData.map(({ id, ...props }) => (
Хорошо

2024-06-10 18:43 UTC, beckyuldashev commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsList/InterviewQuestionsList.tsx
> +				<InterviewQuestionsItem key={id} {...props} />
Исправил

2024-06-10 19:16 UTC, PerelomaDenis commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsItem/InterviewQuestionsItem.tsx
> +			<Link to={`/interview/${link}`} className={styles.link}>
> А разве не /questions/${id}

Да, я опечатался

2024-06-10 19:23 UTC, PerelomaDenis commented on src/widgets/InterviewQuestions/ui/InterviewQuestionHeader/InterviewQuestionHeader.tsx
> +export const InterviewQuestionHeader: FC<Props> = ({ title, linkTitle }) => {
Давай пока что не выносить. Оставь так. Как доверстаешь все блоки, тогда подумаем над рефакторингом

2024-06-10 19:23 UTC, PerelomaDenis commented on src/widgets/InterviewQuestions/ui/InterviewQuestionHeader/InterviewQuestionHeader.tsx
> +				<Link to="/interview/questions" className={styles.link}>
> Просто на questions? Не /interview/questions?

Да, по идее эта ссылка должна вести на обычный список задач не относящийся к интервью

2024-06-11 07:09 UTC, PerelomaDenis submitted a review, later dismissed

2024-06-11 07:25 UTC, MirgradR approved these changes

2024-06-11 08:50 UTC, alexandkazakov submitted a review, later dismissed

2024-06-11 14:30 UTC, alexandkazakov approved these changes

2024-06-11 14:30 UTC, dedushkaalex approved these changes

2024-06-11 14:32 UTC, merged