feature/YH-368 add: phone InputMask, fix: validation
YeaHubTeam/yeahub-platform pull request #119
Opened 2024-09-29 12:44 UTC by makcimishevskih

2024-09-30 08:10 UTC, PerelomaDenis commented on src/features/registration/ui/RegisterForm/RegisterForm.module.css
> +.phone {
Давай вынесем InputPhone в shared  и соответственно стили туда же. А то сейчас дубляж идет. Можешь в принципе компонент также назвать, а импортируя из библиотеки внутри поменять название

2024-09-30 08:39 UTC, alexandkazakov submitted a review, later dismissed

2024-09-30 09:37 UTC, Buffik requested changes

2024-09-30 09:37 UTC, Buffik commented on src/widgets/registration/model/lib/validation/registerSchema.ts
> +		.matches(/^\+7-\(\d{3}\)-\d{3}-\d{2}-\d{2}$/, 'Неверный формат телефона')
здесь мы будем получать ошибку, так как формат телефона, который мы получаем с сервера отличается от формата телефона, с которым ты его сравниваешь здесь. Поэтому при первом клике на поле телефона у тебя вылетает ошибка. Нужно привести формат "+79998887766" (именно такую строку мы получаем с сервера) в "+7-(999)-888-77-66". Это можно сделать в хэлпере mapProfileToForm, изменив profile.user.phone

2024-10-01 11:27 UTC, PerelomaDenis approved these changes

2024-10-01 12:21 UTC, alexandkazakov approved these changes

2024-10-01 12:38 UTC, Buffik approved these changes

2024-10-01 16:01 UTC, merged