YH-206: add tooltip interview page questions list
YeaHubTeam/yeahub-platform pull request #123
Opened 2024-10-01 18:58 UTC by hhpo4

2024-10-02 19:34 UTC, Buffik requested changes

2024-10-02 19:34 UTC, Buffik commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsItem/InterviewQuestionsItem.tsx
>  						<QuestionParam label={t('questions.rating')} value={rate} />
у меня некорректно отображается тултип 
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/c74035ba-dd4d-43f5-9aac-870a359082fc">
система MacOS, темная тема в системе

2024-10-02 19:34 UTC, Buffik commented on src/widgets/InterviewQuestions/ui/InterviewQuestionsItem/InterviewQuestionsItem.module.css
> +    width: clamp(120px, 25vw - 20px, 350px);
максимальное значение ширины для заголовка задано некорректно, он обрезается, когда еще есть место для отображения 
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/682ce47f-3622-413b-b799-0caff8151f9c">

2024-10-03 08:06 UTC, alexandkazakov approved these changes

2024-10-03 15:15 UTC, Buffik commented
Ломается: 

![image](https://github.com/user-attachments/assets/1595635b-9545-42ce-9682-4a2d6dd99c95)

2024-10-10 08:21 UTC, Buffik approved these changes

2024-10-31 15:48 UTC, closed without merging