feature/YH-376: add adaptive
YeaHubTeam/yeahub-platform pull request #124
Opened 2024-10-02 21:09 UTC by hhpo4

2024-10-03 08:25 UTC, alexandkazakov commented on src/widgets/Profile/ui/UserCard/ui/UserEditButton/UserEditButton.module.css
> +@media (width <= 360px) {
Наверное лучше переходить на мобилку с 768 и меньше пикселей, так как получается вот такое на 370 пикс к примеру
![image](https://github.com/user-attachments/assets/125e821b-8b3c-447d-ae2a-79fd551047ea)

2024-10-03 08:25 UTC, alexandkazakov commented on src/widgets/Profile/ui/UserCard/ui/UserEditButton/UserEditButton.module.css
> +@media (width <= 360px) {
И, кстати, кнопка бургер меню у нас куда то пропала. Но тут наверное отдельной задачей надо фиксить. Как Денис скажет

2024-10-03 08:31 UTC, Buffik commented
Когда делаешь адаптив, нужно проверять не только контрольные значения, где перестраивается макет, но и промежуточные, чтобы ничего никуда не уезжало 
![image](https://github.com/user-attachments/assets/10f24147-4e46-4eae-a0fc-83c3188ab7ea)

2024-10-03 08:33 UTC, Buffik requested changes

2024-10-03 08:33 UTC, Buffik commented on src/widgets/Profile/ui/UserCard/ui/UserEditButton/UserEditButton.tsx
> +				onClick={() => navigate('edit#personal-information')}
не нужно использовать анонимные функции в обработчике событий, вынеси в отдельный хэлпер и его же используй в иконке ниже

2024-10-03 15:10 UTC, Buffik submitted a review, later dismissed

2024-10-03 15:10 UTC, Buffik commented on src/widgets/Profile/ui/UserCard/ui/UserEditButton/UserEditButton.tsx
> +	const navigateToEdit = () => navigate('edit#personal-information');
давай уделим время неймингу. Все хендлеры принято называть с handle

2024-10-09 17:54 UTC, PerelomaDenis commented on src/widgets/Profile/ui/UserCard/ui/UserBlock/UserBlock.module.css
> +@media (width <= 1440px) {
с 13 по 31 строку удали

2024-10-09 17:54 UTC, PerelomaDenis commented on src/pages/ProfilePage/ui/ProfilePage.module.css
> +@media (width <= 1024px) {
Вот тут сделай 1440

2024-10-13 17:47 UTC, PerelomaDenis approved these changes

2024-10-13 17:49 UTC, makcimishevskih approved these changes

2024-10-13 17:49 UTC, merged