YH-344: New sidebar menu
YeaHubTeam/yeahub-platform pull request #144
Opened 2024-10-09 21:43 UTC by V4nden

2024-10-10 08:42 UTC, Buffik requested changes

2024-10-10 08:42 UTC, Buffik commented on src/widgets/Sidebar/ui/SidebarMenuItem/SidebarMenuItem.module.css
> +  background-color: var(--color-black-25);
нельзя напрямую использовать цвета из палеты, иначе при смене темы, они изменяться не будут. В данном случае нужно использовать --background-app

2024-10-10 08:42 UTC, Buffik commented on src/widgets/Sidebar/ui/SidebarMenuItem/SidebarMenuItem.module.css
> +  color: var(--color-purple-700);
та же самая ошибка

2024-10-10 08:42 UTC, Buffik commented on src/widgets/Sidebar/ui/SidebarMenuItem/SidebarMenuItem.module.css
> +  background-color: var(--color-black-30);
заменить

2024-10-10 08:42 UTC, Buffik commented on src/widgets/Sidebar/ui/SidebarMenuItem/SidebarMenuItem.module.css
> +  background-color: var(--color-black-30);
заменить (далее прошу пройтись по файлам, самостоятельно найти такие ошибки и поправить их)

2024-10-11 06:53 UTC, Buffik requested changes

2024-10-11 10:28 UTC, Buffik approved these changes

2024-10-12 19:53 UTC, PerelomaDenis commented on src/widgets/Sidebar/ui/SidebarMenuItem/SidebarMenuItem.tsx
> +			<button className={styles.container} onClick={handleExpand}>
Для этой кнопки надо сделать высоту 30px

2024-10-12 19:53 UTC, PerelomaDenis commented on src/widgets/Sidebar/ui/SidebarMenuItem/SidebarMenuItem.tsx
> +		<div
В макете так 
![image](https://github.com/user-attachments/assets/6ae81be6-fd18-4155-8e4c-2ededbfcc41f)
У тебя вот так
![image](https://github.com/user-attachments/assets/9f8471f5-ec00-47c3-87f8-0da286ad1cec)

2024-10-12 19:53 UTC, PerelomaDenis commented on src/widgets/Sidebar/ui/SidebarMenuItem/SidebarMenuItem.tsx
> +	return menuItem.type == 'category' ? (
Давай оба варианта вынесем в отдельные компоненты, а то тяжело читать

2024-10-13 17:17 UTC, PerelomaDenis approved these changes

2024-10-13 17:18 UTC, sam-dash approved these changes

2024-10-13 17:22 UTC, merged