feat (YH-192) add InterviewPreparationBlock
YeaHubTeam/yeahub-platform pull request #19
Opened 2024-06-25 18:22 UTC by sam-dash

2024-06-25 19:35 UTC, PerelomaDenis commented on src/entities/interview/model/data/questionsData.ts
> +export const QUESTIONS_DATA = [
Нужно дать понять, что эти вопросы относятся именно к собесам. Так как скорее всего здесь будет отличаться структура от стандартного вопроса. 
То есть везде внутри папки entities/interview поменяй question -> interviewQuestion. Так как будет отдельная сущность entities со стандартными вопросами

2024-06-25 19:35 UTC, PerelomaDenis commented on src/widgets/InterviewPreparation/ui/QuestionSlider/QuestionSlider.module.css
> +.image-wrapper::after {
Вот тут проще же для класса .question добавить
```
	border-bottom: thin solid var(--color-black-400)
```
вместо псевдоэлемента

2024-06-25 19:47 UTC, sam-dash commented on src/widgets/InterviewPreparation/ui/QuestionSlider/QuestionSlider.module.css
> +.image-wrapper::after {
Делала вчера ночью и почему-то border была толще. Сейчас смотрю и все ок, хз что было

2024-06-25 19:58 UTC, PerelomaDenis commented on src/widgets/InterviewPreparation/ui/QuestionSlider/QuestionSlider.module.css
> +.image-wrapper::after {
Это может быть из-за изменения размеров экрана. Бывает такое, что ты указываешь 1px. Но у тебя окно браузера на половину открыто к примеру, и показывает как будто у тебя например 0.5px

2024-06-26 10:37 UTC, MirgradR approved these changes

2024-06-26 12:16 UTC, Buffik requested changes

2024-06-26 12:16 UTC, Buffik commented on src/entities/interview/ui/QuestionNavPanel/QuestionNavPanel.module.css
> +  background-color: var(--color-white-900);
не нужно использовать цвета из color-palette, бери цвета из тем, в данном случае правильное значение --background-block

Всё настроено так, что при переключении режима (темная / светлая тема), эти цвета будут автоматически меняться

2024-06-26 12:16 UTC, Buffik commented on src/entities/interview/ui/QuestionNavPanel/QuestionNavPanel.module.css
> +    color: var(--color-purple-700);
тоже самое: цвета из тем

2024-06-26 12:16 UTC, Buffik commented on src/entities/interview/ui/QuestionNavPanel/QuestionNavPanel.module.css
> +      color: var(--color-purple-700);
тоже самое: цвета из тем

2024-06-26 12:16 UTC, Buffik commented on src/entities/interview/ui/QuestionProgressBar/QuestionProgressBar.module.css
> +    background-color: var(--color-purple-700);
тоже самое: цвета из тем. Дальше пропускаю такие ошибки, просьба посмотреть все стили

2024-06-27 05:53 UTC, Buffik approved these changes

2024-06-28 14:16 UTC, PerelomaDenis approved these changes

2024-06-28 18:02 UTC, MirgradR approved these changes

2024-06-28 18:48 UTC, merged