feat (YH-193) make a passed questions statistics component
YeaHubTeam/yeahub-platform pull request #22
Opened 2024-06-29 19:27 UTC by beckyuldashev

1) Оставил пока пустую ссылку для перехода на страницу общей статистики
2) Прогресс можно начать слева, как в макете, но оставил пока, чтобы начинался сверху. Если надо могу переделать
3) При переключении темы, тайтл посередине прогресса не меняет цвет, эту проблему решим позже

2024-06-30 07:54 UTC, Serhio46 commented on src/shared/ui/LinkWithArrowRight/ui/LinkWithArrowRight.tsx
> +import ArrowRightIcon from '@/shared/assets/icons/arrowRight.svg';
У нас в uikit есть компонент Icon, лучше взять оттуда

2024-06-30 07:54 UTC, Serhio46 commented on src/shared/ui/LinkWithArrowRight/ui/LinkWithArrowRight.tsx
> +export const LinkWithArrowRight: FC<Props> = ({ link, linkTitle }) => {
FC договорились не использовать, типизировать пропсы const LinkWithArrowRight = ({ link, linkTitle }: Props)

2024-06-30 07:54 UTC, Serhio46 commented on src/shared/ui/PassedQuestionStat/ui/PassedQuestionStat.tsx
> +	const gaugeData = [
вынести из компоненты, сдедать baseSettings или baseConfig, туда же options

2024-06-30 07:54 UTC, Serhio46 commented on src/shared/ui/PassedQuestionStat/ui/PassedQuestionStat.tsx
> +			<ReactECharts
Подумать сделать базовый компонент, типа BaseChart с базовыми сеттнингами, то что написал выше так же в базовый компонент. А уже в PassedQuestionStat и других местах его использовать.

2024-06-30 09:44 UTC, alexandkazakov reviewed
При мердже у нас образовался пустой блок, нужно пофиксить
![image](https://github.com/YeaHubTeam/yeahub-platform/assets/81985267/71b5a2d3-c97b-49cc-944e-801823539673)

2024-06-30 09:44 UTC, alexandkazakov commented on src/widgets/InterviewQuestions/ui/InterviewQuestionHeader/InterviewQuestionHeader.tsx
> +			{Boolean(linkTitle) && <LinkWithArrowRight link="/questions" linkTitle={linkTitle} />}
Для удобства можно !!linkTitle

2024-06-30 09:59 UTC, beckyuldashev commented on src/shared/ui/LinkWithArrowRight/ui/LinkWithArrowRight.tsx
> +import ArrowRightIcon from '@/shared/assets/icons/arrowRight.svg';
Хорошо, тогда поменяю и других местах, где этот ArrowRightIcon использовался

2024-06-30 10:01 UTC, beckyuldashev commented on src/widgets/InterviewQuestions/ui/InterviewQuestionHeader/InterviewQuestionHeader.tsx
> +			{Boolean(linkTitle) && <LinkWithArrowRight link="/questions" linkTitle={linkTitle} />}
Точно, спасибо. Насчет блока да, я тоже заметил, исправлю

2024-06-30 20:06 UTC, PerelomaDenis commented on src/shared/ui/PassedQuestionStat/ui/PassedQuestionStat.tsx
> +				startAngle: 90,
Вот тут поменяй на 
```
startAngle: 0,
endAngle: 360,
```
Так как по макету начало графика идет не сверху а справа

2024-06-30 20:06 UTC, PerelomaDenis commented on src/shared/ui/PassedQuestionStat/ui/PassedQuestionStat.tsx
> +	// const option = {
УБрать комменты

2024-06-30 20:40 UTC, beckyuldashev commented on src/shared/ui/PassedQuestionStat/ui/PassedQuestionStat.tsx
> +	const gaugeData = [
Решил оставить пока как есть

2024-06-30 20:41 UTC, beckyuldashev commented on src/shared/ui/PassedQuestionStat/ui/PassedQuestionStat.tsx
> +			<ReactECharts
Хорошо, оставлю как есть

2024-06-30 20:56 UTC, PerelomaDenis submitted a review, later dismissed

2024-07-01 04:10 UTC, Buffik requested changes

2024-07-01 04:10 UTC, Buffik commented on src/shared/ui/LinkWithArrowRight/ui/LinkWithArrowRIght.module.css
> +  color: var(--color-purple-700);
нужно использовать переменные из тем, в данном случае подойдет --text-color-link-active

2024-07-01 06:13 UTC, Serhio46 approved these changes

2024-07-01 08:06 UTC, PerelomaDenis approved these changes

2024-07-01 08:50 UTC, merged