Feature/yh 98
YeaHubTeam/yeahub-platform pull request #30
Opened 2024-07-18 19:25 UTC by TeRovaWork

И так, я тут все раскидал. Вроде по структуре проекта должно быть правильно, но это не точно. Есть пара мелочей которые надо добавить из макета, но это я оставил себе на сладкое.

Пока жду вашего ревью (/≧▽≦)/  ...(*￣０￣)ノ

2024-07-18 22:02 UTC, PerelomaDenis requested changes

2024-07-18 22:02 UTC, PerelomaDenis commented on src/widgets/ProfileEducationCard/ui/EducationCardItem/EducationCardItem.tsx
> +			<span className={styles['separator']}></span>
Этот блок можно вынести в компонент shared/ui/Divider

2024-07-19 04:43 UTC, TeRovaWork commented on src/widgets/ProfileEducationCard/ui/EducationCardItem/EducationCardItem.tsx
> +			<span className={styles['separator']}></span>
> Этот блок можно вынести в компонент shared/ui/Divider

Это ты про сепаратор ?

2024-07-21 18:19 UTC, PerelomaDenis approved these changes

2024-07-21 19:41 UTC, sam-dash approved these changes

2024-07-22 10:28 UTC, merged