feat (YH-77) add reuseble block component
YeaHubTeam/yeahub-platform pull request #4
Opened 2024-04-14 16:38 UTC by Perfect1onn

2024-04-14 17:18 UTC, MirgradR approved these changes

2024-04-14 17:18 UTC, MirgradR commented on src/pages/Profile/ui/Profile.tsx
>  export const Profile: FC = () => {
Надо конкретно назвать
ProfilePage?

2024-04-14 17:18 UTC, MirgradR commented on src/widgets/Block/ui/Block.tsx
> +export const Block: FC<Props> = ({
ощущение что слишком сложный компонент

2024-04-14 17:18 UTC, MirgradR commented on src/pages/Profile/ui/Profile.tsx
> +			<Block
мб в карточку вынесем? ProfileCard

2024-04-14 17:18 UTC, MirgradR commented on src/pages/Profile/ui/Profile.tsx
> +			<Block title="Обо мне" expandable actionSlot={<div>Редактировать</div>}>
мб ProfileAbout - энтити

2024-04-14 17:25 UTC, Perfect1onn commented on src/pages/Profile/ui/Profile.tsx
> +			<Block
Да, согласен но я просто добавил для примера использования.

2024-04-14 17:26 UTC, Perfect1onn commented on src/pages/Profile/ui/Profile.tsx
> +			<Block title="Обо мне" expandable actionSlot={<div>Редактировать</div>}>
Согласен

2024-04-14 17:27 UTC, Perfect1onn commented on src/widgets/Block/ui/Block.tsx
> +export const Block: FC<Props> = ({
Да, но я попытался чтобы он был максимально переиспользуемым. Но в целом можно какие то части декомпозировать в более маленькие компоненты.

2024-04-15 11:59 UTC, alexandkazakov requested changes

2024-04-15 11:59 UTC, alexandkazakov commented on src/widgets/Block/ui/Block.module.css
> +  transition: all 300ms ease-in-out;
Задавать all - плохая практика, сильно нагружает/может нагрузить браузер. В данном случае, можно сделать так:
`transition: padding-bottom 0.3s ease-in-out, max-height 0.3s ease-in-out;`

2024-04-15 11:59 UTC, alexandkazakov commented on src/widgets/Block/ui/Block.module.css
> +  background-color: var(--color-white-900);
Используй переменную `--background-block`, чтобы при смене темы автоматически цвет менялся

2024-04-15 11:59 UTC, alexandkazakov commented on src/widgets/Block/ui/Block.module.css
> +  transition: 300ms ease-in-out;
Тут также даем transition только для свойства transform: `transition: transform 0.3s ease-in-out;`.

2024-04-15 11:59 UTC, alexandkazakov commented on src/widgets/Block/ui/Block.tsx
> +			${isHeightForExpand && expandable && styles['block-expandable']}
Стили по условию лучше делать через тернарный оператор: `isHeightForExpand && expandable ? styles['block-expandable'] : ''`
Иначе получается false в class у элемента:
![image](https://github.com/YeaHubTeam/yeahub-platform/assets/81985267/40693dc1-9914-4e1b-8c4b-21743e37241f)

2024-04-15 11:59 UTC, alexandkazakov commented on src/widgets/Block/ui/Block.module.css
> +  max-height: 250px;
Из-за того, что у нас меняется max-height, хоть его и добавил в transition, но он отрабатывает неровно на некоторых масштабах. Надо попробовать найти какое то решение

https://github.com/YeaHubTeam/yeahub-platform/assets/81985267/5175b02a-101e-4306-a7dd-a8bcfccdd5d4

2024-04-15 13:11 UTC, PerelomaDenis commented on src/widgets/Block/ui/Block.tsx
> +			${isHeightForExpand && expandable && styles['block-expandable']}
Добавьте библиотеку classnames - удобнее будет работать, когда стилей много на одном элементе.
Будет вот так примерно выглядеть
`className={classNames(styles.block, { 
    [styles['block-expandable']]: isHeightForExpand && expandable ,
    [ styles['block-expanded']]: !isExpand
}
`

2024-04-15 13:14 UTC, alexandkazakov commented on src/pages/Main/ui/MainPage.tsx
> +export const MainPage: FC = () => {
Согласен, BundleAnalyzerPlugin() уже есть в моем ПР, там закомментирован, но всегда можно раскоменнтить и открыть

2024-04-15 14:08 UTC, alexandkazakov commented on src/widgets/Block/ui/Block.tsx
> +			${isHeightForExpand && expandable && styles['block-expandable']}
> Добавьте библиотеку classnames - удобнее будет работать, когда стилей много на одном элементе. Будет вот так примерно выглядеть `className={classNames(styles.block, { [styles['block-expandable']]: isHeightForExpand && expandable , [ styles['block-expanded']]: !isExpand } `

Я раньше постоянно использовал, но потом как-то ушел от этого. Использую обычно только когда очень сложные условия. Ну в принципе, в данном случае, на усмотрение Самира бы оставил. Условие не такое сложное, но и не совсем простое)

2024-04-15 16:06 UTC, Yuriykant commented on src/pages/Main/ui/MainPage.tsx
> +export const MainPage: FC = () => {
Это влияет на метрику LCP тестить лучше при следующих условиях: fast 3g, disabled cache.

2024-04-18 12:46 UTC, PerelomaDenis submitted a review, later dismissed

2024-04-19 10:22 UTC, alexandkazakov commented on src/widgets/Block/ui/Block.module.css
> +  transition: max-height 300ms ease-in-out, padding-bottom 450ms ease-in-out;
Сюда еще добавить надо background-color, т.к. при смене темы нет анимации на блоке

2024-04-19 10:22 UTC, alexandkazakov commented on src/widgets/Block/ui/Block.module.css
> +  max-height: 250px;
При тесте, снова такая же проблема. Особенно заметно, если блок большой и скрыто много. Анимация срабатывает за то же время, а двигаться ей надо сильно дальше.
Честно, сам с таким не встречался, но вообще желательно поискать какой то выход из ситуации. Мб применять js/либы?

2024-04-20 09:38 UTC, PerelomaDenis submitted a review, later dismissed

2024-04-23 07:16 UTC, PerelomaDenis commented on src/widgets/Block/ui/Block.tsx
> +					<svg
Надо бы вынести svg отдельно

2024-04-23 08:34 UTC, alexandkazakov approved these changes

2024-04-23 08:34 UTC, alexandkazakov approved these changes

2024-04-23 09:29 UTC, PerelomaDenis approved these changes

2024-04-23 09:36 UTC, MirgradR approved these changes

2024-04-23 15:02 UTC, merged