add open/close sidebar, connect rtk query
YeaHubTeam/yeahub-platform pull request #5
Opened 2024-04-17 22:43 UTC by AleksanderIazev

2024-04-20 09:43 UTC, PerelomaDenis approved these changes

2024-04-22 06:55 UTC, alexandkazakov requested changes
Также посмотри что происходит при смене темы, нужно поправить.
Также по поводу иконки сворачивания/разворачивания: нужно что то красивее. Как минимум, поставить чтобы цвет фона был по вертикальной линии иконки, плюс надо сделать разворот иконки.

А вообще, нужно обратиться к дизайнерам, чтобы они проработали перенос иконки в место, где она не будет перемещаться при сворачивании/разворачивании сайбара

2024-04-22 06:55 UTC, alexandkazakov commented on src/app/layouts/MainLayout/MainLayout.module.css
> +.closing{
Используй пробел между наименованием класса и фигурной скобкой везде

2024-04-22 06:55 UTC, alexandkazakov commented on src/app/layouts/MainLayout/MainLayout.tsx
> +import { NavSidebarList } from '@/widgets/NavigationSidebar';
Что-то не то у тебя с виджетом NavSideBar. Всю папку NavigationSidebar надо удалить и использовать только NavSidebar

2024-04-22 06:55 UTC, alexandkazakov commented on src/app/layouts/MainLayout/MainLayout.tsx
> +		<section className={`${styles.layout} ${isOpenSidebar && styles.closing}`}>
Для добавления класса по условию используй тернарный оператор. Иначе у тебя в наименовании класса будет присутствовать false

2024-04-22 06:55 UTC, alexandkazakov commented on src/app/layouts/MainLayout/MainLayout.tsx
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Для чего выключаешь ESLint?

2024-04-22 06:55 UTC, alexandkazakov commented on src/shared/ui/AppLogo/AppLogo.tsx
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Для чего выключаешь ESlint?

2024-04-22 06:55 UTC, alexandkazakov commented on src/shared/ui/AppLogo/AppLogo.tsx
> +	const isOpenSidebar = useSelector((state: any) => state.navigationSidebar.isOpenSidebar);
Для типизации useSelector нужно использовать useAppSelector

2024-04-22 06:55 UTC, alexandkazakov commented on src/shared/ui/AppLogo/AppLogo.tsx
> +		<NavLink to="/" className={`${styles.logo} ${isOpenSidebar && styles.one}`}>
Опять же, для классов по условию используем тернарный оператор

2024-04-22 06:55 UTC, alexandkazakov commented on src/shared/ui/AppLogo/AppLogo.tsx
> +			<Logo className={`${styles.name} ${isOpenSidebar && styles.closing}`} />
Для классов по условию используем тернарный оператор

2024-04-22 06:55 UTC, alexandkazakov commented on src/widgets/NavigationSidebar/model/slice.ts
> +export const navigationsSidebarSlice = createSlice({
Очень длинное название
Как минимум, navSidebarSlice
И вообще, а нужно ли нам в сторе хранить состояние? Мб использовать стейт?

2024-04-22 06:55 UTC, alexandkazakov commented on src/widgets/NavigationSidebar/ui/NavSidebarItem/NavSidebarItem.tsx
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Для чего выключаешь?

2024-04-22 06:55 UTC, alexandkazakov commented on src/widgets/NavigationSidebar/ui/NavSidebarItem/NavSidebarItem.tsx
> +				<span className={`${styles.span} ${isOpenSidebar && styles.closing}`}>{title}</span>
Тернарный оператор

2024-04-24 07:47 UTC, alexandkazakov requested changes

2024-04-24 07:47 UTC, alexandkazakov commented on src/shared/assets/icons/close-sidebar.svg
Можно удалять

2024-04-24 07:47 UTC, alexandkazakov commented on src/shared/assets/icons/open-sidebar.svg
Можно удалять

2024-04-24 07:47 UTC, alexandkazakov commented on src/shared/assets/images/logoImg.png
Иконка имеет плохое разрешение. Обратись к дизайнерам в их чат, надо решить эту проблему

2024-04-24 07:47 UTC, alexandkazakov commented on src/shared/ui/AppLogo/AppLogo.module.css
> +.logo-image{
Не забывай пробел перед скобкой. Проверь все такие случае в своем ПР

2024-04-24 07:47 UTC, alexandkazakov commented on src/widgets/NavSidebar/ui/NavSidebarItem/NavSidebarItem.tsx
> +interface INavItemProps {
Давай называть без буквы I, чтобы одинаково везде было

2024-04-24 07:47 UTC, alexandkazakov commented on src/widgets/NavSidebar/ui/NavSidebarList/NavSidebarList.module.css
> +  border: solid var(--color-black-800);
Думаю уместно дать значение var(--text-color-primary)

2024-04-24 07:47 UTC, alexandkazakov commented on src/widgets/NavSidebar/ui/NavSidebarList/NavSidebarList.module.css
> +  opacity:0.7
Пробел, точка с запятой. Проверь, мб у тебя не включен prettier

2024-04-24 07:47 UTC, alexandkazakov commented on src/widgets/NavSidebar/ui/NavSidebarList/NavSidebarList.module.css
> +  transition: color 0.3s ease-in-out, opacity .3s ease-in;
Добавить background-color

2024-04-24 07:47 UTC, alexandkazakov commented on src/shared/assets/images/logoImg.png
А также, может сделать иверсивную иконку? Белый фон, черные линии для темной темы? Переговори в дизайнерском чате

2024-04-24 07:47 UTC, alexandkazakov commented on src/widgets/NavSidebar/ui/NavSidebarList/NavSidebarList.module.css
> +.arrow {
Стрелка смещена влево или вправо в зависимости от ее поворота. Как вариант, можно рассмотреть svg вместо отрисовки через CSS или центр поворота смещать

2024-04-24 07:47 UTC, alexandkazakov commented on src/widgets/NavSidebar/ui/NavSidebarList/NavSidebarList.module.css
> +  transform: rotate(135deg);
А зачем 2 одинаковых свойста?

2024-04-24 07:47 UTC, alexandkazakov commented on src/widgets/NavSidebar/ui/NavSidebarList/NavSidebarList.module.css
> +  transform: rotate(-180deg);
И тут тоже 2 одинаковых свойства

2024-04-24 07:47 UTC, alexandkazakov commented on src/widgets/NavSidebar/ui/NavSidebarList/NavSidebarList.module.css
> +  transform: rotate(135deg);
Добавить transition для transform: rotate

2024-04-30 14:13 UTC, PerelomaDenis approved these changes

2024-04-30 14:29 UTC, alexandkazakov commented on src/features/common/search-input/ui/SearchInput.module.css
>    transition: border-color .3s ease-in-out;
Заметил, что вот тут в transition нет background-color, добавь плз

2024-04-30 14:29 UTC, alexandkazakov commented on src/widgets/NavSidebar/ui/NavSidebarList/NavSidebarList.module.css
>    transition: color 0.3s ease-in-out;
В transition не хватает transform для плавного разворота стрелки

2024-05-01 07:00 UTC, alexandkazakov approved these changes

2024-05-02 05:15 UTC, Perfect1onn approved these changes

2024-05-02 05:15 UTC, merged