feat (YH-264) add filter for calendar history quiz
YeaHubTeam/yeahub-platform pull request #68
Opened 2024-08-30 07:31 UTC by stepanchaban

- Добавил к запросу на получение истории квизов фильтр по дате из календаря с помощью параметров startAfter и startBefore

2024-08-30 07:53 UTC, Buffik requested changes

2024-08-30 07:53 UTC, Buffik commented on src/widgets/FullInterviewHistory/ui/FullInterviewHistoryList/FullInterviewHistoryList.tsx
> +export const FullInterviewHistoryList: React.FC<FullInterviewHistoryListProps> = ({ data }) => {
не нужно так типизировать компонент. 

export const FullInterviewHistoryList = ({ data }: FullInterviewHistoryListProps) =>

2024-08-30 07:53 UTC, Buffik commented on src/widgets/FullInterviewHistory/ui/FullInterviewHistoryList/FullInterviewHistoryList.tsx
> +	// eslint-disable-next-line react/prop-types
убери отключение eslint. И, если он на что-то ругается, то это повод задуматься, что ты делаешь что-то не так, а не отключать его))

2024-08-30 07:53 UTC, Buffik commented on src/widgets/FullInterviewHistory/ui/FullInterviewHistoryList/FullInterviewHistoryList.tsx
> +						// eslint-disable-next-line react/prop-types
тоже самое

2024-08-30 07:55 UTC, stepanchaban commented on src/widgets/FullInterviewHistory/ui/FullInterviewHistoryList/FullInterviewHistoryList.tsx
> +	// eslint-disable-next-line react/prop-types
proptypes использовать гуд или нет?

2024-08-30 08:05 UTC, Serhio46 commented on src/shared/ui/Calendar/EventCalendar.tsx
> +
Переделай компонент внутри, как я понимаю стейт просто сделали, так как снаружи не хендлили, передай в onChange={setDate} вместо setDate, тот проп  onDateChange

2024-08-30 08:08 UTC, stepanchaban commented on src/shared/ui/Calendar/EventCalendar.tsx
> +
так будет ошибка

2024-08-30 08:38 UTC, PerelomaDenis commented on src/widgets/FullInterviewHistory/ui/FullInterviewHistoryList/FullInterviewHistoryList.tsx
> +	data?: QuizHistoryResponse[];
Не надо называть пропсы, переменные слишком общими названиями. Такой подход нейминга выдает разработчика в небольшой количестве опыта. Всегда выбирай название так, чтобы сразу было понятно что там лежит. Так как data просто говорит о том, что это какие то данные. А вот например quizesHistory сразу говорит о содержимом

2024-08-30 08:38 UTC, PerelomaDenis commented on src/shared/ui/Calendar/EventCalendar.tsx
> +	useEffect(() => {
Сейчас тут происходит жуткая каша 
У тебя есть стейт тут в календаре, на изменение стейта ты вызываешь useEffect который сетит значение даты в другой стейт который лежит на странице. К тому же у тебя эти 2 стейта имеют хоть и похожие, но в то же время и разные интерфейсы, хотя данные одинаковые
Собственно что надо сделать - стейт из календаря перенести вместе с типами на уровень страницы. А тот стейт что ты добавлял удалить . Проверить чт овсе работает и дальше уже перенести хранение и изменение даты в редакс

2024-08-30 10:27 UTC, Buffik submitted a review, later dismissed

2024-08-30 17:30 UTC, PerelomaDenis commented on src/pages/InterviewHistoryPage/model/selectors/InterviewHistoryPageSelectors.ts
> +export const getInterviewHistoryPageFilter = (state: State) => state.interviewHistoryPage.dateRange;
Назови getInterviewHistoryPageDateRange 
Старайся учитывать, что могут появиться другие параметры для фильтров, и чтобы тебе не пришлось потом переименовывать текущий

2024-08-30 17:30 UTC, PerelomaDenis commented on src/pages/InterviewHistoryPage/model/slices/InterviewHistoryPageSlice.ts
> +	name: 'filterDate',
Назови interviewHistoryPage и сделай вот так 
![image](https://github.com/user-attachments/assets/1e95e0ea-eeee-4e12-8657-6f3c0f4f5bac)

2024-08-30 17:30 UTC, PerelomaDenis commented on src/pages/InterviewHistoryPage/ui/InterviewHistoryPage.tsx
> +						startBefore: dateRange[1] ? dateRange[1].toISOString() : undefined,
Сделай вот так 
![image](https://github.com/user-attachments/assets/1dc02b13-9618-4ccf-a77f-7e604bbcc626)

2024-08-30 17:30 UTC, PerelomaDenis commented on src/pages/InterviewHistoryPage/model/types/InterviewHistoryPageType.ts
> +	dateRange: [Date | null, Date | null];
Сделай вот так 
![image](https://github.com/user-attachments/assets/4c39ca36-6f29-41a9-a16c-df258dfebb5a)

2024-08-30 17:30 UTC, PerelomaDenis commented on src/shared/ui/Calendar/EventCalendar.tsx
> +	const handleDateChange = (dates: Value) => {
Эта функция бесполезна здесь. Можно просто указать onDateChange в onChange
Сделай вот так 
![image](https://github.com/user-attachments/assets/7a0aef68-7ca7-46b3-baff-5c83bd4a8268)

2024-08-30 17:30 UTC, PerelomaDenis commented on src/shared/ui/Calendar/EventCalendar.tsx
> +}
И можешь сразу же изменить немного структуру этой папки
```
EventCalendar
    ui
        EventCalendar.tsx
        EventCalendar.module.css
    index.ts
```

2024-08-31 13:23 UTC, PerelomaDenis approved these changes

2024-08-31 14:03 UTC, PerelomaDenis approved these changes

2024-09-01 07:31 UTC, alexandkazakov submitted a review, later dismissed

2024-09-01 16:10 UTC, Buffik approved these changes

2024-09-02 06:05 UTC, PerelomaDenis approved these changes

2024-09-02 06:52 UTC, alexandkazakov approved these changes

2024-09-02 06:53 UTC, merged