Feature/yh 287
YeaHubTeam/yeahub-platform pull request #75
Opened 2024-09-01 14:34 UTC by alexandkazakov

2024-09-01 16:06 UTC, Buffik requested changes

2024-09-01 16:06 UTC, Buffik commented on src/widgets/NavSidebar/model/category.ts
> +	[ROUTES.interview.page]: 'Собеседование',
забыл про перевод на английский. Предлагаю либо прям здесь заюзать i18n, либо указать путь до json'a и потом в компоненте NavSidebarItem использовать i18n

2024-09-01 17:23 UTC, Buffik submitted a review, later dismissed

2024-09-02 00:06 UTC, PerelomaDenis commented on src/entities/question/ui/QuestionPreview/QuestionPreview.tsx
> +								<NavLink className={styles.link} to={`${ROUTES.interview.questions.page}/${id}`}>
При таком подходе будет работать только если id будет вконце
Например в админке есть пути такие, что id стоит в середине
Предлагаю добавить такой хелпер
```
const route = (path: string, ...params: Array<string | number>) => {
		let count = -1;
		return path.replace(/:[a-zA-Z?]+/g, function (match) {
			count += 1;
			return String(params[count] !== undefined ? params[count] : match);
		});
	};
```
Также добавить в ROUTES например к этому роуту ключ detail: ':questionId'
И в итоге использовать вот так
```
route(ROUTES.interview.questions.detail, id)
```
Суть в том, что найдет все значения имеющие двоеточие и заменить на то, что мы передали 2 и далее параметрами по порядку

2024-09-07 10:47 UTC, PerelomaDenis approved these changes

2024-09-07 14:03 UTC, sam-dash approved these changes

2024-09-07 14:23 UTC, merged