bug/YH-300 clear activeQuizState after send form
YeaHubTeam/yeahub-platform pull request #78
Opened 2024-09-02 20:03 UTC by makcimishevskih

2024-09-03 13:45 UTC, Buffik requested changes

2024-09-03 13:45 UTC, Buffik commented on src/entities/quiz/api/quizApi.ts
> +			},
не нужно так делать. Если ты хочешь скинуть кэш на каком-то конкретном эндпоинте, то просто нужно инвалидировать тэг. В этом запросе есть строка providesTags: [ApiTags.INTERVIEW_QUIZ]. Здесь же в файле есть saveQuizResult, в нем можно добавить строчку invalidatesTags:[ApiTags.INTERVIEW_QUIZ]

2024-09-04 10:30 UTC, Buffik requested changes

2024-09-04 10:30 UTC, Buffik commented on src/pages/InterviewPage/ui/InterviewPage.tsx
> +						link={!isActiveQuizExist ? 'quiz/interviewQuiz' : 'quiz'}
Нужно вернуть как было, это ломает всю логику.
Плюс к моему комменту про форсрефеч: а если мы получим пустой массив с активным квизом, то есть активных квизов нет, стартдейт все равно появится в ЛС, соответственно этот линк будет перекидывать на страницу прохождения квиза, которого нет, что приведет к некорректному поведению приложения.

Либо нужно делать проверку в API на то, что входящие данные - это не пустой массив и только потом сетать в ЛС, либо выносить в компонент. Второе, на мой взгляд, предпочтительнее. Лучше дождаться комментария от @PerelomaDenis

2024-09-04 16:55 UTC, PerelomaDenis commented on src/entities/quiz/api/quizApi.ts
> +			},
Да, это явно стоит убрать

2024-09-04 16:55 UTC, PerelomaDenis commented on src/pages/InterviewPage/ui/InterviewPage.tsx
> +	const isActiveQuizExist = !!startDate;
Верни как было. А то сейчас будет некорректно работать, так как изначально в стейте пустое значение, а надо брать актуальное из лс

2024-09-04 16:55 UTC, PerelomaDenis commented on src/pages/InterviewPage/ui/InterviewPage.tsx
> +						link={!isActiveQuizExist ? 'quiz/interviewQuiz' : 'quiz'}
Да, тут тоже вернуть как было. Изменять логику будем потом менять

2024-09-04 16:55 UTC, PerelomaDenis commented on src/pages/InterviewQuizPage/ui/InterviewQuizPage.tsx
> +
Для этой страницы потерялись хлебные крошки, добавь дял этого роута в routeConfig.ts
```
handle: { crumb: 'Викторина' },
```

2024-09-04 18:07 UTC, PerelomaDenis approved these changes

2024-09-04 18:14 UTC, Buffik approved these changes

2024-09-04 18:35 UTC, merged