add Tabs, add editProfilePage
YeaHubTeam/yeahub-platform pull request #8
Opened 2024-05-08 02:02 UTC by ArturSha

промежуточный коммит.
![image](https://github.com/YeaHubTeam/yeahub-platform/assets/108091184/def00e27-7944-444b-b285-2f80d1ade733)
тут каждый блок выносить в entities?

так же хотел уточнить как правильно сделать компонент Tabs. если использовать <li/> то идут нарушение со стороны esLint. так как Ли не является кнопкой. правильно будет использовать button или же просто навешивать на Li доп обработчики что бы избежать замечаний со стороны линта ?

2024-05-08 06:35 UTC, PerelomaDenis commented
> промежуточный коммит. ![image](https://private-user-images.githubusercontent.com/108091184/328728284-def00e27-7944-444b-b285-2f80d1ade733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNDk3NDEsIm5iZiI6MTcxNTE0OTQ0MSwicGF0aCI6Ii8xMDgwOTExODQvMzI4NzI4Mjg0LWRlZjAwZTI3LTc5NDQtNDQ0Yi1iMjg1LTJmODBkMWFkZTczMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwNjI0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzVjOTI5NTgyOGExY2FlZjhiNmY2MmIyM2EzMGYwNzVmMzRiMmZiMjViNmI2NjQwZTJkYTQ4ZjNiMDU0YjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9q8F-9tk38uIq9SJwZpvwVWrt-lHThGrPNjLEzdWYAw) тут каждый блок выносить в entities?
> 
> так же хотел уточнить как правильно сделать компонент Tabs. если использовать li то идут нарушение со стороны esLint. так как Ли не является кнопкой. правильно будет использовать button или же просто навешивать на Li доп обработчики что бы избежать замечаний со стороны линта ?

Насчет табов сильно не парься, так как табы будут в uikit. Насчет контента, в целом это все будет одна большая feature, которая будет включать в себя одну большую форму, хоть и разделенную на табы. Образование, навыки, опыт работы и образование, это отдельные сущности, а первые 2 таба будут относиться к сущности профиля

2024-05-08 06:37 UTC, PerelomaDenis commented on src/app/providers/router/config/routeConfig.tsx
> +				path: 'editProfile',
лучше не писать camelCase. Лучше сделай такой путь profile/edit как логичное продолжение основной страницы профиля

2024-05-09 18:26 UTC, PerelomaDenis commented on src/entities/Education/ui/Education.tsx
> +import { Input, Label } from 'yeahub-ui-kit';
Все сущности в маленькой буквы называй. 
Название компонент не может быть равно названию сущности, так как не несет никакой информации о том, что в ней лежит. Назови лучше компоненту Education как EducationForm, чтобы сразу было понятно, что лежит внутри. И так с остальными тоже
Также можно было бы наверное еще декомпозировать компоненты, но думаю на этом этапе не так критично.

2024-06-05 16:41 UTC, alexandkazakov commented
Нужно контентную часть перенести в центр. Как на странице профиля. 
![image](https://github.com/YeaHubTeam/yeahub-platform/assets/81985267/e5b47a45-eb29-4c29-87a6-5c339a8f132f)

2024-06-05 16:54 UTC, alexandkazakov commented
Нужно переделать немного структуру.

Есть 2 варианта на мой взгляд:
1. В "pages/EditProfilePage" должна быть страница c заголовком, куда будешь вставлять одну большую фичу (напрример, EditProfileForm), где в каждом табе будут использоваться свои сущности: первые два таба - сущность User, таб Навыки - сущность Skill, таб Проекты - сущность Project, таб Опыт работы - сущность Experience, таб Образование - сущность Education. В каждой сущности будут свои компоненты: PersonalInfoProfileForm, AboutMeProfileForm и т.д. 

2 вариант. В "pages/EditProfilePage" должна быть страница c заголовком и табами, а в каждом табе ты будешь вызывать формы из сущностей, как по первому варианту.

Тут надо пробовать и понять какой вариант лучше. Вроде как форма одна, поэтому вроде как фича одна, а внутри уже формы из сущностей.
Но вообще я бы убрал кнопки далее и делал бы сохранить кнопку. Чтобы разделить эти формы на разные. Как будто это логичнее и безопаснее для пользака

2024-06-05 16:56 UTC, alexandkazakov requested changes

2024-06-05 16:56 UTC, alexandkazakov commented on src/entities/EditProfileForms/ui/EducationForm/EducationForm.tsx
> +import cls from './EducationForm.module.css';
А почему ты называешь cls? Впервые прост вижу такое обозначение. Как расшифровывается?
Обычно style или styles

2024-06-17 22:52 UTC, ArturSha commented on src/entities/EditProfileForms/ui/EducationForm/EducationForm.tsx
> +import cls from './EducationForm.module.css';
привык так с проекта от ulbi ) но могу исправить на style.

2024-06-30 08:20 UTC, ArturSha commented on src/entities/Education/ui/Education.tsx
> +import { Input, Label } from 'yeahub-ui-kit';
исправил

2024-07-01 17:20 UTC, PerelomaDenis submitted a review, later dismissed

2024-07-01 17:20 UTC, Buffik submitted a review, later dismissed

2024-07-01 17:21 UTC, PerelomaDenis approved these changes

2024-07-01 17:21 UTC, Buffik approved these changes

2024-07-01 17:21 UTC, merged