feat: (YH-166) replaced the btns group with the SettingsButton component
YeaHubTeam/yeahub-platform pull request #9
Opened 2024-06-08 11:36 UTC by sam-dash

Добавила компонент с иконкой настроек. Удалила лишние иконки.

2024-06-08 12:03 UTC, MirgradR commented on src/shared/ui/SettingsButton/SettingsButton.tsx
> +import { FC } from 'react';
если пропсов нет, можно не добавлять это

2024-06-08 12:03 UTC, MirgradR commented on src/shared/ui/SettingsButton/SettingsButton.tsx
> +		<button className={styles.button} type="button" aria-label="Settings">
возможно есть Компонент в ui (в нашей библиотеке yeahub-ui-kit), <IconButton />
import {IconButton} from 'yeahub-ui-kit'

2024-06-08 12:12 UTC, dedushkaalex commented on src/shared/ui/UserPreferences/UserPreferences.tsx
> +			<div className={styles.sittings}>
settings

2024-06-10 18:26 UTC, alexandkazakov requested changes

2024-06-10 18:34 UTC, Serhio46 commented on src/shared/ui/UserPreferences/UserPreferences.module.css
> +  cursor: pointer;
В Iconbutton есть пропс, iconClassName, попробуй на него навесить

2024-06-11 08:56 UTC, alexandkazakov approved these changes

2024-06-11 08:56 UTC, alexandkazakov commented on src/features/common/search-input/index.ts
> +// export { SearchInput } from './ui/SearchInput';
А почему закомментила? ts вроде не должен ругаься

2024-06-11 08:56 UTC, alexandkazakov commented on src/features/common/search-input/index.ts
> +// export { SearchInput } from './ui/SearchInput';
Из-за подключения к будущему компоненту?

2024-06-11 09:38 UTC, sam-dash commented on src/features/common/search-input/index.ts
> +// export { SearchInput } from './ui/SearchInput';
Это я затупила. Сначала закомментировала, а потом начала из хедера выносить. Уберу со следующей таской

2024-06-11 10:03 UTC, MirgradR approved these changes

2024-06-11 11:24 UTC, merged